// CARDS CONVIDA
export const cardsConvida = [
  {
    topico: "ABERTURA",
    horario: "09:00",
    tipo: "card-topico",
  },
  {
    nome: "JEAN LIVINO",
    nomeArquivoImagem: "jean-livino.webp",
    cargo: "Desenvolvedor Front-End iFood",
    assunto: "A realidade de trabalhar em projetos que usam IA",
    linkedin: "jeanlivino",
    instagram: "jeanlivino",
    horario: "09:15",
    tipo: "card-palestrante",
  },
  {
    nome: "CJ PATOILO",
    nomeArquivoImagem: "cj-patoilo.webp",
    cargo: "Criador do Miligram.io e Airform.io",
    assunto: "Frontend Patterns - Uma perspectiva moderna da arquitetura de software",
    instagram: "cjpatoilo",
    linkedin: "cjpatoilo",
    horario: "09:30",
    tipo: "card-palestrante",
  },
  {
    topico: "NETWORKING",
    horario: "10:00",
    tipo: "card-topico",
  },
  {
    nome: "BRUNO BARROSO",
    nomeArquivoImagem: "bruno-barroso.webp",
    cargo: "Tech Project Manager Doutor Finanças - Portugal",
    assunto: "Carreira & Tecnologia & Bacalhau",
    instagram: "brunorbarroso",
    linkedin: "brunorbarroso",
    horario: "10:40",
    tipo: "card-palestrante",
  },
  {
    nome: "WESLEY JONATHA",
    nomeArquivoImagem: "wesley-jonatha.webp",
    cargo: "Desenvolvedor Stefanini",
    assunto:
      "Introdução ao Golang e Micro Serviços: Eficiência e Escalabilidade",
    instagram: "wesleyj.dev",
    linkedin: "wesley-jonatha-9329ba18a",
    horario: "11:00",
    tipo: "card-palestrante",
  },
  {
    nome: "TIME PMENOS LAB",
    nomeArquivoImagem: "time-pmenos-lab.webp",
    cargo: "Líderes Times de Inovação, Hub de Saúde, Ecommerce e App",
    assunto: "Ecossistema VTEX e Alavancando Resultados com um App Gerencial",
    instagram: "pmenoslab",
    linkedin: "",
    horario: "11:20",
    tipo: "card-palestrante",
  },
  {
    nome: "CAMILA GADELHA",
    nomeArquivoImagem: "camila-gadelha.webp",
    cargo: "UX Designer Sistema Verdes Mares",
    assunto: "Pesquisa com usuários - A importância de ouvir quem usa o produto",
    instagram: "camilafgadelha",
    linkedin: "camilafgadelha",
    horario: "11:40",
    tipo: "card-palestrante",
  },
  {
    topico: "INTERVALO ALMOÇO",
    horario: "12:00",
    tipo: "card-topico",
  },
  {
    nome: "VINÍCIUS CAMPITELLI",
    nomeArquivoImagem: "vinicius-campitelli.webp",
    cargo: " Developer Relations FusionAuth",
    assunto: "O que você precisa saber sobre autenticação com JWT",
    instagram: "vcampitelli",
    linkedin: "viniciuscampitelli",
    horario: "13:30",
    tipo: "card-palestrante",
  },
  {
    nome: "VICTOR ALENCAR",
    nomeArquivoImagem: "victor-alencar.webp",
    cargo: "CTO Sunne Energias",
    assunto: "Do Console à Sala de Reunião: profissionalismo na entrevista e na empresa",
    instagram: "",
    linkedin: "",
    horario: "13:50",
    tipo: "card-palestrante",
  },

  {
    nome: "MATHEUS LOUREIRO",
    nomeArquivoImagem: "matheus-loureiro.webp",
    cargo: "Co-Founder e Idealizador de soluções bh2",
    assunto: "Tecnologia e Finanças. O que temos de oportunidade?",
    instagram: "",
    linkedin: "callmeloureiro",
    horario: "14:10",
    tipo: "card-palestrante",
  },
  {
    nome: "RENATA E KEL",
    nomeArquivoImagem: "renata-e-kel.webp",
    cargo: "Sócias Evo Contábil",
    assunto: "Contabilidade básica para o empreendedor, PJ e CLT",
    instagram: "evocontabil",
    linkedin: "",
    horario: "14:30",
    tipo: "card-palestrante",
  },
  {
    nome: "MILENA TAVEIRA",
    nomeArquivoImagem: "milena-taveira.webp",
    cargo: " UX Designer LSBD",
    assunto: "Transição de carreira: migrando para UX",
    instagram: "milenatav",
    linkedin: "taveiram",
    horario: "14:50",
    tipo: "card-palestrante",
  },
  {
    nome: "AMÁLIA MOURA",
    nomeArquivoImagem: "amalia-moura.webp",
    cargo: "Especialista em carreira Rocketseat",
    assunto: "Além dos Códigos: Tudo que você precisa saber para conquistar sua vaga",
    instagram: "amaliabeatrizmoura",
    linkedin: "amáliabeatrizmoura",
    horario: "15:10",
    tipo: "card-palestrante",
  },
  {
    nome: "RACHEL CARVALHO",
    nomeArquivoImagem: "rachel-carvalho.webp",
    cargo: "Product Designer Agenda Edu",
    assunto: "UX e Handoff, a passagem do designer para o dev",
    instagram: "kellrcarvalho",
    linkedin: "kellrcarvalho",
    horario: "15:30",
    tipo: "card-palestrante",
  },
  {
    topico: "COFFEE BREAK + NETWORKING",
    horario: "15:50",
    tipo: "card-topico",
  },
  {
    topico: "SORTEIOS DE BRINDES E PARTICIPANTES DO CODANDO NO BREU",
    horario: "16:45",
    tipo: "card-topico",
  },
  {
    nome: "WILLIAN FRANTZ",
    nomeArquivoImagem: "willian-frantz.webp",
    cargo: "Senior Software Engineer Riot Games",
    assunto: "Código nos jogos: Minha experiência na Riot Games",
    instagram: "",
    linkedin: "willianfrantz",
    horario: "17:00",
    tipo: "card-palestrante",
  },
  {
    nome: "ADRIANA SATY",
    nomeArquivoImagem: "adriana-saty.webp",
    cargo: "Criadora de Conteúdo WebSaty",
    assunto: "Data Driven na vida pessoal",
    instagram: "adriana.saty",
    linkedin: "adriana-saty",
    horario: "17:30",
    tipo: "card-palestrante",
  },
  {
    topico: "ENCERRAMENTOS DAS PALESTRAS",
    horario: "18:00",
    tipo: "card-topico",
  },
  {
    topico: "CODANDO NO BREU | CODE IN THE DARK",
    horario: "18:30",
    tipo: "card-topico",
  },
];