export const cardsFrontEnd = [
  {
    topico: "ABERTURA",
    horario: "09:00",
    tipo: "card-topico",
  },
  {
    nome: "JEAN LIVINO",
    nomeArquivoImagem: "jean-livino.webp",
    cargo: "Desenvolvedor Front-End iFood",
    assunto: "A realidade de trabalhar em projetos que usam IA",
    linkedin: "jeanlivino",
    instagram: "jeanlivino",
    horario: "09:15",
    tipo: "card-palestrante",
  },
  {
    nome: "CJ PATOILO",
    nomeArquivoImagem: "cj-patoilo.webp",
    cargo: "Criador do Miligram.io e Airform.io",
    assunto: "Frontend Patterns - Uma perspectiva moderna da arquitetura de software",
    instagram: "cjpatoilo",
    linkedin: "cjpatoilo",
    horario: "09:30",
    tipo: "card-palestrante",
  },
  {
    topico: "NETWORKING",
    horario: "10:00",
    tipo: "card-topico",
  },
  // {
  //   nome: "BRUNO BARROSO",
  //   nomeArquivoImagem: "bruno-barroso.webp",
  //   cargo: "Tech Project Manager Doutor Finanças - Portugal",
  //   assunto: "Carreira & Tecnologia & Bacalhau",
  //   instagram: "brunorbarroso",
  //   linkedin: "brunorbarroso",
  //   horario: "10:20",
  //   tipo: "card-palestrante",
  // },
  {
    nome: "AMANDA ESMERALDO",
    nomeArquivoImagem: "amanda-esmeraldo.webp",
    cargo: "Frontend Developer Grupo Boticário",
    assunto: "Composition ou Opposition API: Por que tamanha resistência?",
    instagram: "alomands",
    linkedin: "aesmeraldo",
    horario: "10:40",
    tipo: "card-palestrante",
  },
  {
    nome: "LUCAS ALMEIDA",
    nomeArquivoImagem: "lucas-almeida.webp",
    cargo: "Senior Software Engineering Chilli Piper",
    assunto: "Explorando React Server Components",
    instagram: "tsirlucas",
    linkedin: "tsirlucas",
    horario: "11:00",
    tipo: "card-palestrante",
  },
  {
    nome: "JOÃO WILLAMY",
    nomeArquivoImagem: "joao-willamy.webp",
    cargo: "Senior Software Engineering iFood",
    assunto: "E2E com Cypress",
    instagram: "joaowillamyy",
    linkedin: "joao-willamy",
    horario: "11:20",
    tipo: "card-palestrante",
  },
  {
    nome: "BRUNO SILVA",
    nomeArquivoImagem: "bruno-silva.webp",
    cargo: "Full Stack Developer Unimed",
    assunto: "Angular e Inteligência Artificial: Como integrar IA em Aplicações Web",
    instagram: "brumsilva",
    linkedin: "brumsilva",
    horario: "11:40",
    tipo: "card-palestrante",
  },
  {
    topico: "INTERVALO ALMOÇO",
    horario: "12:00",
    tipo: "card-topico",
  },
  {
    nome: "HEYDE MOURA",
    nomeArquivoImagem: "heyde-moura.webp",
    cargo: "Senior Software Engineer Automattic",
    assunto: "React para extender o Editor de Blocos do WordPress",
    instagram: "",
    linkedin: "heyde-moura-3387a67b",
    horario: "13:30",
    tipo: "card-palestrante",
  },
  {
    nome: "FELIPE CÉSAR",
    nomeArquivoImagem: "felipe-cesar.webp",
    cargo: "Desenvolvedor Front-End Globo",
    assunto: "React com TDD: Da Teoria à Prática",
    instagram: "felipecesr",
    linkedin: "felipecesr",
    horario: "13:50",
    tipo: "card-palestrante",
  },
  {
    nome: "ISMAEL ASH",
    nomeArquivoImagem: "ismael-ash.webp",
    cargo: "Senior Software Developer 3blocks",
    assunto: "React.js para entrevistas",
    instagram: "oismaelash",
    linkedin: "oismaelash",
    horario: "14:10",
    tipo: "card-palestrante",
  },
  {
    nome: "IAN RAMOS",
    nomeArquivoImagem: "ian-ramos.webp",
    cargo: "Senior Software Engineer Automattic",
    assunto: "Como ter um pet pode te ajudar a ser um programador melhor",
    instagram: "ianramosc_",
    linkedin: "ianramosc",
    horario: "14:30",
    tipo: "card-palestrante",
  },
  {
    nome: "ELOISE FERREIRA",
    nomeArquivoImagem: "eloise-ferreira.webp",
    cargo: "Desenvolvedora Front-End IREDE",
    assunto: "Inclusão Digital: WCAG e Acessibilidade na Web",
    instagram: "",
    linkedin: "eloise-ferreira",
    horario: "14:50",
    tipo: "card-palestrante",
  },
  {
    nome: "KEVIN TAVARES",
    nomeArquivoImagem: "kevin-tavares.webp",
    cargo: "Software Engineer Elo7",
    assunto: "Progressive Enhancement: O que é e como usá-lo?",
    instagram: "kevinbtv",
    linkedin: "kevinbtv",
    horario: "15:10",
    tipo: "card-palestrante",
  },
  {
    nome: "ABRAÃO ALVES",
    nomeArquivoImagem: "abraao-alves.webp",
    cargo: "Software Engineer Beakyn",
    assunto: "Typescript Morreu! Vida Longa ao Typescript!",
    instagram: "abraao.alves_",
    linkedin: "abraaoalves",
    horario: "15:30",
    tipo: "card-palestrante",
  },
  {
    topico: "COFFEE BREAK + NETWORKING",
    horario: "15:50",
    tipo: "card-topico",
  },
  {
    topico: "SORTEIOS DE BRINDES E PARTICIPANTES DO CODANDO NO BREU",
    horario: "16:45",
    tipo: "card-topico",
  },
  {
    nome: "WILLIAN FRANTZ",
    nomeArquivoImagem: "willian-frantz.webp",
    cargo: "Senior Software Engineer Riot Games",
    assunto: "Código nos jogos: Minha experiência na Riot Games",
    instagram: "willianluigi",
    linkedin: "willianfrantz",
    horario: "17:00",
    tipo: "card-palestrante",
  },
  {
    nome: "ADRIANA SATY",
    nomeArquivoImagem: "adriana-saty.webp",
    cargo: "Criadora de Conteúdo WebSaty",
    assunto: "Data Driven na vida pessoal",
    instagram: "adriana.saty",
    linkedin: "adriana-saty",
    horario: "17:30",
    tipo: "card-palestrante",
  },
  {
    topico: "ENCERRAMENTOS DAS PALESTRAS",
    horario: "18:00",
    tipo: "card-topico",
  },
  {
    topico: "CODANDO NO BREU | CODE IN THE DARK",
    horario: "18:30",
    tipo: "card-topico",
  },
];